<?php
$store = Mage::helper('shariff')->checkStore();
$current_cms = Mage::getSingleton('cms/page')->getIdentifier();
$status = Mage::helper('shariff')->checkStatus();
$cms_page_status = Mage::helper('shariff')->checkCmsPageStatus();
$cmsbottom_status = Mage::helper('shariff')->checkCmsBottomStatus();
$shariff_services_status = Mage::helper('shariff')->shariffSerivcesStatus("status");
$shariff_services = Mage::helper('shariff')->shariffSerivcesStatus("services");
$shariff_language = Mage::helper('shariff')->shariffLanguage($store->getLocaleCode());
$shariff_design = Mage::helper('shariff')->shariffDesign();
$shariff_designposition = Mage::helper('shariff')->shariffDesignPosition();
$shariff_cms_page = Mage::helper('shariff')->getCmsPages();
if($status){
    if(in_array($current_cms, $shariff_cms_page) && $cms_page_status == 1){
    if($cmsbottom_status){
?>
    <div class="shariff" <?php if($shariff_services_status != ''){ ?>data-services='[<?php echo $shariff_services ; ?>]'<?php } ?> data-lang="<?php echo $shariff_language ; ?>" data-theme="<?php echo $shariff_design ; ?>" data-orientation="<?php echo $shariff_designposition ; ?>"></div>
<?php } } } ?>

